M48
; DRILL file {KiCad 9.0.2} date 2025-08-03T00:22:58-0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-08-03T00:22:58-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X120.2Y-59.8
X120.2Y-89.5
X151.7Y-59.8
X151.7Y-89.5
M30
